<a href="https://colab.research.google.com/github/divyanshuraj25/Day_18_LLM_Hallucination_Measurement/blob/main/Day_18_Hallucination_Measurement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Day 18 - Hallucination Measurement")
print("Setup started successfully!")

Day 18 - Hallucination Measurement
Setup started successfully!

In [ ]:
!pip install -q google-genai

In [ ]:
print("Colab is working!")

Colab is working!

In [ ]:
import os
from getpass import getpass

api_key = getpass("Enter your Gemini API key: ")

os.environ["GEMINI_API_KEY"] = api_key

print("Gemini API key loaded successfully!")

Enter your Gemini API key: ··········
Gemini API key loaded successfully!

In [ ]:
import pandas as pd

questions = [
    # Science
    {
        "id": 1,
        "domain": "Science",
        "question": "What is the chemical formula of water?",
        "ground_truth": "H2O"
    },
    {
        "id": 2,
        "domain": "Science",
        "question": "What planet is known as the Red Planet?",
        "ground_truth": "Mars"
    },
    {
        "id": 3,
        "domain": "Science",
        "question": "What gas do humans need to breathe for cellular respiration?",
        "ground_truth": "Oxygen"
    },
    {
        "id": 4,
        "domain": "Science",
        "question": "What is the boiling point of water at standard atmospheric pressure in Celsius?",
        "ground_truth": "100 degrees Celsius"
    },
    {
        "id": 5,
        "domain": "Science",
        "question": "What force keeps planets in orbit around the Sun?",
        "ground_truth": "Gravity"
    },

    # Technology
    {
        "id": 6,
        "domain": "Technology",
        "question": "What does CPU stand for?",
        "ground_truth": "Central Processing Unit"
    },
    {
        "id": 7,
        "domain": "Technology",
        "question": "What does RAM stand for?",
        "ground_truth": "Random Access Memory"
    },
    {
        "id": 8,
        "domain": "Technology",
        "question": "What programming language was created by Guido van Rossum?",
        "ground_truth": "Python"
    },
    {
        "id": 9,
        "domain": "Technology",
        "question": "What does HTTP stand for?",
        "ground_truth": "Hypertext Transfer Protocol"
    },
    {
        "id": 10,
        "domain": "Technology",
        "question": "What does AI stand for?",
        "ground_truth": "Artificial Intelligence"
    },

    # General Knowledge
    {
        "id": 11,
        "domain": "General Knowledge",
        "question": "What is the capital of France?",
        "ground_truth": "Paris"
    },
    {
        "id": 12,
        "domain": "General Knowledge",
        "question": "How many continents are there on Earth?",
        "ground_truth": "Seven"
    },
    {
        "id": 13,
        "domain": "General Knowledge",
        "question": "What is the largest ocean on Earth?",
        "ground_truth": "Pacific Ocean"
    },
    {
        "id": 14,
        "domain": "General Knowledge",
        "question": "Which language has the most native speakers in the world?",
        "ground_truth": "Mandarin Chinese"
    },
    {
        "id": 15,
        "domain": "General Knowledge",
        "question": "What is the currency of Japan?",
        "ground_truth": "Japanese Yen"
    },

    # History
    {
        "id": 16,
        "domain": "History",
        "question": "Who was the first President of the United States?",
        "ground_truth": "George Washington"
    },
    {
        "id": 17,
        "domain": "History",
        "question": "In which year did World War II end?",
        "ground_truth": "1945"
    },
    {
        "id": 18,
        "domain": "History",
        "question": "Which ancient civilization built the pyramids at Giza?",
        "ground_truth": "Ancient Egyptians"
    },
    {
        "id": 19,
        "domain": "History",
        "question": "Who wrote the Declaration of Independence of the United States?",
        "ground_truth": "Thomas Jefferson is generally credited as the principal author"
    },
    {
        "id": 20,
        "domain": "History",
        "question": "Which empire built the Colosseum in Rome?",
        "ground_truth": "The Roman Empire"
    }
]

df = pd.DataFrame(questions)

print("Dataset created successfully!")
print("Total questions:", len(df))

df

Dataset created successfully!
Total questions: 20

,id,domain,question,ground_truth
0,1,Science,What is the chemical formula of water?,H2O
1,2,Science,What planet is known as the Red Planet?,Mars
2,3,Science,What gas do humans need to breathe for cellula...,Oxygen
3,4,Science,What is the boiling point of water at standard...,100 degrees Celsius
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity
5,6,Technology,What does CPU stand for?,Central Processing Unit
6,7,Technology,What does RAM stand for?,Random Access Memory
7,8,Technology,What programming language was created by Guido...,Python
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol
9,10,Technology,What does AI stand for?,Artificial Intelligence
10,11,General Knowledge,What is the capital of France?,Paris
11,12,General Knowledge,How many continents are there on Earth?,Seven
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean
13,14,General Knowledge,Which language has the most native speakers in...,Mandarin Chinese
14,15,General Knowledge,What is the currency of Japan?,Japanese Yen
15,16,History,Who was the first President of the United States?,George Washington
16,17,History,In which year did World War II end?,1945
17,18,History,Which ancient civilization built the pyramids ...,Ancient Egyptians
18,19,History,Who wrote the Declaration of Independence of t...,Thomas Jefferson is generally credited as the ...
19,20,History,Which empire built the Colosseum in Rome?,The Roman Empire

In [ ]:
from google import genai
import os
import time

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

responses = []

for _, row in df.iterrows():

    prompt = f"""
Answer the following factual question accurately and concisely.

Question: {row['question']}

Give only the answer. Do not invent facts.
"""

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        answer = response.text.strip()

    except Exception as e:
        answer = f"ERROR: {e}"

    responses.append(answer)

    print(f"Question {row['id']}/20 completed")
    time.sleep(1)

df["llm_answer"] = responses

print("\nAll 20 questions completed!")

df[["id", "domain", "question", "llm_answer"]]

Question 1/20 completed
Question 2/20 completed
Question 3/20 completed
Question 4/20 completed
Question 5/20 completed
Question 6/20 completed
Question 7/20 completed
Question 8/20 completed
Question 9/20 completed
Question 10/20 completed
Question 11/20 completed
Question 12/20 completed
Question 13/20 completed
Question 14/20 completed
Question 15/20 completed
Question 16/20 completed
Question 17/20 completed
Question 18/20 completed
Question 19/20 completed
Question 20/20 completed

All 20 questions completed!

,id,domain,question,llm_answer
0,1,Science,What is the chemical formula of water?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
1,2,Science,What planet is known as the Red Planet?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
2,3,Science,What gas do humans need to breathe for cellula...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
3,4,Science,What is the boiling point of water at standard...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
4,5,Science,What force keeps planets in orbit around the Sun?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
5,6,Technology,What does CPU stand for?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
6,7,Technology,What does RAM stand for?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
7,8,Technology,What programming language was created by Guido...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
8,9,Technology,What does HTTP stand for?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
9,10,Technology,What does AI stand for?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
10,11,General Knowledge,What is the capital of France?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
11,12,General Knowledge,How many continents are there on Earth?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
12,13,General Knowledge,What is the largest ocean on Earth?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
13,14,General Knowledge,Which language has the most native speakers in...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
14,15,General Knowledge,What is the currency of Japan?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
15,16,History,Who was the first President of the United States?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
16,17,History,In which year did World War II end?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
17,18,History,Which ancient civilization built the pyramids ...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
18,19,History,Who wrote the Declaration of Independence of t...,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."
19,20,History,Which empire built the Colosseum in Rome?,"ERROR: 404 NOT_FOUND. {'error': {'code': 404, ..."

In [ ]:
from google import genai
import os

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

models = client.models.list()

for model in models:
    print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-omni-1.1-flash
models/gemini-3.5-transcribe
models/gemini-3.6-flash
models/gemini-3.7-flash
models/gemini-3.8-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/lyria-3.5
models/gemini-3.1-flash-tts-preview
models/gemini-3.8-flash-tts
models/gemini-3.8-flash-lite-tts
models/gemini-robotics-er-2-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/antigravity-preview-09-2026
models/antigravity-preview-latest
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-3.5-transcribe-live
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview
models/gemini-3.8-live
models/gemini-3.8-live-extended-thinking
models/gemini-robotics-er-2-streaming-preview
models/gemini-3.5-live-translate-preview
models/lyria-realtime-exp

In [ ]:
model="gemini-2.5-flash"

In [ ]:
models = client.models.list()

for model in models:
    print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-omni-1.1-flash
models/gemini-3.5-transcribe
models/gemini-3.6-flash
models/gemini-3.7-flash
models/gemini-3.8-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/lyria-3.5
models/gemini-3.1-flash-tts-preview
models/gemini-3.8-flash-tts
models/gemini-3.8-flash-lite-tts
models/gemini-robotics-er-2-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/antigravity-preview-09-2026
models/antigravity-preview-latest
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-3.5-transcribe-live
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview
models/gemini-3.8-live
models/gemini-3.8-live-extended-thinking
models/gemini-robotics-er-2-streaming-preview
models/gemini-3.5-live-translate-preview
models/lyria-realtime-exp

In [ ]:
from google import genai
import os

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents="What is the chemical formula of water? Answer briefly."
)

print(response.text)

The chemical formula of water is **H₂O**.

In [ ]:
import time

responses = []

for _, row in df.iterrows():
    prompt = f"""
Answer the following factual question accurately and concisely.

Question: {row['question']}

Give only the answer. Do not invent facts.
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )
        answer = response.text.strip()

    except Exception as e:
        answer = f"ERROR: {e}"

    responses.append(answer)

    print(f"Question {row['id']}/20 completed")
    time.sleep(1)

df["llm_answer"] = responses

print("\nAll 20 questions completed!")

df[[
    "id",
    "domain",
    "question",
    "ground_truth",
    "llm_answer"
]]

Question 1/20 completed
Question 2/20 completed
Question 3/20 completed
Question 4/20 completed
Question 5/20 completed
Question 6/20 completed
Question 7/20 completed
Question 8/20 completed
Question 9/20 completed
Question 10/20 completed
Question 11/20 completed
Question 12/20 completed
Question 13/20 completed
Question 14/20 completed
Question 15/20 completed
Question 16/20 completed
Question 17/20 completed
Question 18/20 completed
Question 19/20 completed
Question 20/20 completed

All 20 questions completed!

,id,domain,question,ground_truth,llm_answer
0,1,Science,What is the chemical formula of water?,H2O,H2O
1,2,Science,What planet is known as the Red Planet?,Mars,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...
2,3,Science,What gas do humans need to breathe for cellula...,Oxygen,Oxygen
3,4,Science,What is the boiling point of water at standard...,100 degrees Celsius,100 °C
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity,Gravity
5,6,Technology,What does CPU stand for?,Central Processing Unit,Central Processing Unit
6,7,Technology,What does RAM stand for?,Random Access Memory,Random Access Memory
7,8,Technology,What programming language was created by Guido...,Python,Python
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol
9,10,Technology,What does AI stand for?,Artificial Intelligence,Artificial Intelligence
10,11,General Knowledge,What is the capital of France?,Paris,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
11,12,General Knowledge,How many continents are there on Earth?,Seven,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
13,14,General Knowledge,Which language has the most native speakers in...,Mandarin Chinese,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
14,15,General Knowledge,What is the currency of Japan?,Japanese Yen,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
15,16,History,Who was the first President of the United States?,George Washington,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
16,17,History,In which year did World War II end?,1945,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
17,18,History,Which ancient civilization built the pyramids ...,Ancient Egyptians,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
18,19,History,Who wrote the Declaration of Independence of t...,Thomas Jefferson is generally credited as the ...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...
19,20,History,Which empire built the Colosseum in Rome?,The Roman Empire,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...

In [ ]:
df["evaluation"] = ""
df["hallucination_type"] = ""

print("Evaluation table ready!")
print("Total responses:", len(df))

df[[
    "id",
    "domain",
    "question",
    "ground_truth",
    "llm_answer",
    "evaluation",
    "hallucination_type"
]]

Evaluation table ready!
Total responses: 20

,id,domain,question,ground_truth,llm_answer,evaluation,hallucination_type
0,1,Science,What is the chemical formula of water?,H2O,H2O,,
1,2,Science,What planet is known as the Red Planet?,Mars,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,,
2,3,Science,What gas do humans need to breathe for cellula...,Oxygen,Oxygen,,
3,4,Science,What is the boiling point of water at standard...,100 degrees Celsius,100 °C,,
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity,Gravity,,
5,6,Technology,What does CPU stand for?,Central Processing Unit,Central Processing Unit,,
6,7,Technology,What does RAM stand for?,Random Access Memory,Random Access Memory,,
7,8,Technology,What programming language was created by Guido...,Python,Python,,
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,,
9,10,Technology,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,,
10,11,General Knowledge,What is the capital of France?,Paris,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
11,12,General Knowledge,How many continents are there on Earth?,Seven,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
13,14,General Knowledge,Which language has the most native speakers in...,Mandarin Chinese,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
14,15,General Knowledge,What is the currency of Japan?,Japanese Yen,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
15,16,History,Who was the first President of the United States?,George Washington,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
16,17,History,In which year did World War II end?,1945,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
17,18,History,Which ancient civilization built the pyramids ...,Ancient Egyptians,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
18,19,History,Who wrote the Declaration of Independence of t...,Thomas Jefferson is generally credited as the ...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,
19,20,History,Which empire built the Colosseum in Rome?,The Roman Empire,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,,

In [ ]:
def evaluate_answer(ground_truth, answer):
    gt = str(ground_truth).lower().strip()
    ans = str(answer).lower().strip()

    # Error response
    if ans.startswith("error:"):
        return "Hallucinated"

    # Exact or direct match
    if gt in ans or ans in gt:
        return "Correct"

    # Important keywords for partial matches
    gt_words = set(gt.replace(",", "").split())
    ans_words = set(ans.replace(",", "").split())

    overlap = len(gt_words & ans_words) / max(len(gt_words), 1)

    if overlap >= 0.3:
        return "Partially Correct"

    return "Hallucinated"


df["evaluation"] = df.apply(
    lambda row: evaluate_answer(
        row["ground_truth"],
        row["llm_answer"]
    ),
    axis=1
)

print("Evaluation completed!")

df[[
    "id",
    "question",
    "ground_truth",
    "llm_answer",
    "evaluation"
]]

Evaluation completed!

,id,question,ground_truth,llm_answer,evaluation
0,1,What is the chemical formula of water?,H2O,H2O,Correct
1,2,What planet is known as the Red Planet?,Mars,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,Hallucinated
2,3,What gas do humans need to breathe for cellula...,Oxygen,Oxygen,Correct
3,4,What is the boiling point of water at standard...,100 degrees Celsius,100 °C,Partially Correct
4,5,What force keeps planets in orbit around the Sun?,Gravity,Gravity,Correct
5,6,What does CPU stand for?,Central Processing Unit,Central Processing Unit,Correct
6,7,What does RAM stand for?,Random Access Memory,Random Access Memory,Correct
7,8,What programming language was created by Guido...,Python,Python,Correct
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,Correct
9,10,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,Correct
10,11,What is the capital of France?,Paris,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
11,12,How many continents are there on Earth?,Seven,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
12,13,What is the largest ocean on Earth?,Pacific Ocean,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
13,14,Which language has the most native speakers in...,Mandarin Chinese,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
14,15,What is the currency of Japan?,Japanese Yen,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
15,16,Who was the first President of the United States?,George Washington,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
16,17,In which year did World War II end?,1945,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
17,18,Which ancient civilization built the pyramids ...,Ancient Egyptians,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
18,19,Who wrote the Declaration of Independence of t...,Thomas Jefferson is generally credited as the ...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated
19,20,Which empire built the Colosseum in Rome?,The Roman Empire,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,Hallucinated

In [ ]:
evaluation_summary = df["evaluation"].value_counts()

print("=== HALLUCINATION EVALUATION SUMMARY ===")
print(evaluation_summary)

print("\n=== PERCENTAGE ===")
print(
    (df["evaluation"].value_counts(normalize=True) * 100)
    .round(2)
    .astype(str) + "%"
)

=== HALLUCINATION EVALUATION SUMMARY ===
evaluation
Hallucinated         11
Correct               8
Partially Correct     1
Name: count, dtype: int64

=== PERCENTAGE ===
evaluation
Hallucinated         55.0%
Correct              40.0%
Partially Correct     5.0%
Name: proportion, dtype: object

In [ ]:
pd.set_option("display.max_colwidth", 200)

review_df = df[[
    "id",
    "domain",
    "question",
    "ground_truth",
    "llm_answer",
    "evaluation"
]].copy()

review_df

,id,domain,question,ground_truth,llm_answer,evaluation
0,1,Science,What is the chemical formula of water?,H2O,H2O,Correct
1,2,Science,What planet is known as the Red Planet?,Mars,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",Hallucinated
2,3,Science,What gas do humans need to breathe for cellular respiration?,Oxygen,Oxygen,Correct
3,4,Science,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 degrees Celsius,100 °C,Partially Correct
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity,Gravity,Correct
5,6,Technology,What does CPU stand for?,Central Processing Unit,Central Processing Unit,Correct
6,7,Technology,What does RAM stand for?,Random Access Memory,Random Access Memory,Correct
7,8,Technology,What programming language was created by Guido van Rossum?,Python,Python,Correct
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,Correct
9,10,Technology,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,Correct
10,11,General Knowledge,What is the capital of France?,Paris,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
11,12,General Knowledge,How many continents are there on Earth?,Seven,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
13,14,General Knowledge,Which language has the most native speakers in the world?,Mandarin Chinese,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
14,15,General Knowledge,What is the currency of Japan?,Japanese Yen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
15,16,History,Who was the first President of the United States?,George Washington,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
16,17,History,In which year did World War II end?,1945,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
17,18,History,Which ancient civilization built the pyramids at Giza?,Ancient Egyptians,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
18,19,History,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson is generally credited as the principal author,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated
19,20,History,Which empire built the Colosseum in Rome?,The Roman Empire,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",Hallucinated

In [ ]:
# API errors ko hallucination nahi maana jayega
def clean_evaluation(row):
    answer = str(row["llm_answer"]).strip()

    if answer.startswith("ERROR:"):
        return "API Error"

    # Correct known answer for Q4
    if row["id"] == 4 and "100" in answer and "°c" in answer.lower():
        return "Correct"

    return row["evaluation"]


df["evaluation"] = df.apply(clean_evaluation, axis=1)

print("=== CLEANED EVALUATION ===")
print(df["evaluation"].value_counts())

print("\n=== API ERROR COUNT ===")
print((df["evaluation"] == "API Error").sum())

df[[
    "id",
    "question",
    "llm_answer",
    "evaluation"
]]

=== CLEANED EVALUATION ===
evaluation
API Error    11
Correct       9
Name: count, dtype: int64

=== API ERROR COUNT ===
11

,id,question,llm_answer,evaluation
0,1,What is the chemical formula of water?,H2O,Correct
1,2,What planet is known as the Red Planet?,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",API Error
2,3,What gas do humans need to breathe for cellular respiration?,Oxygen,Correct
3,4,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 °C,Correct
4,5,What force keeps planets in orbit around the Sun?,Gravity,Correct
5,6,What does CPU stand for?,Central Processing Unit,Correct
6,7,What does RAM stand for?,Random Access Memory,Correct
7,8,What programming language was created by Guido van Rossum?,Python,Correct
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,Correct
9,10,What does AI stand for?,Artificial Intelligence,Correct
10,11,What is the capital of France?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
11,12,How many continents are there on Earth?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
12,13,What is the largest ocean on Earth?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
13,14,Which language has the most native speakers in the world?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
14,15,What is the currency of Japan?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
15,16,Who was the first President of the United States?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
16,17,In which year did World War II end?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
17,18,Which ancient civilization built the pyramids at Giza?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
18,19,Who wrote the Declaration of Independence of the United States?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
19,20,Which empire built the Colosseum in Rome?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error

In [ ]:
import time

failed_rows = df[df["evaluation"] == "API Error"].copy()

print("Questions to retry:", len(failed_rows))

for idx, row in failed_rows.iterrows():

    prompt = f"""
Answer the following factual question accurately and concisely.

Question: {row['question']}

Give only the answer. Do not invent facts.
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        answer = response.text.strip()

        # Update the original dataframe
        df.loc[idx, "llm_answer"] = answer
        df.loc[idx, "evaluation"] = ""

        print(f"Question {row['id']} retry successful")

    except Exception as e:
        print(f"Question {row['id']} retry failed: {str(e)[:120]}")

    # Wait between requests
    time.sleep(5)

print("\nRetry completed!")

Questions to retry: 11
Question 2 retry failed: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand
Question 11 retry successful
Question 12 retry successful
Question 13 retry successful
Question 14 retry successful
Question 15 retry successful
Question 16 retry failed: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand
Question 17 retry failed: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand
Question 18 retry successful
Question 19 retry successful
Question 20 retry failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and

Retry completed!

In [ ]:
# Evaluate only successful Gemini responses

for idx, row in df.iterrows():
    answer = str(row["llm_answer"]).strip()

    if not answer.startswith("ERROR:"):
        df.loc[idx, "evaluation"] = evaluate_answer(
            row["ground_truth"],
            answer
        )

print("Evaluation updated!")

df[[
    "id",
    "question",
    "ground_truth",
    "llm_answer",
    "evaluation"
]]

Evaluation updated!

,id,question,ground_truth,llm_answer,evaluation
0,1,What is the chemical formula of water?,H2O,H2O,Correct
1,2,What planet is known as the Red Planet?,Mars,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",API Error
2,3,What gas do humans need to breathe for cellular respiration?,Oxygen,Oxygen,Correct
3,4,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 degrees Celsius,100 °C,Partially Correct
4,5,What force keeps planets in orbit around the Sun?,Gravity,Gravity,Correct
5,6,What does CPU stand for?,Central Processing Unit,Central Processing Unit,Correct
6,7,What does RAM stand for?,Random Access Memory,Random Access Memory,Correct
7,8,What programming language was created by Guido van Rossum?,Python,Python,Correct
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,Correct
9,10,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,Correct
10,11,What is the capital of France?,Paris,Paris,Correct
11,12,How many continents are there on Earth?,Seven,7,Hallucinated
12,13,What is the largest ocean on Earth?,Pacific Ocean,Pacific Ocean,Correct
13,14,Which language has the most native speakers in the world?,Mandarin Chinese,Mandarin Chinese,Correct
14,15,What is the currency of Japan?,Japanese Yen,Japanese yen,Correct
15,16,Who was the first President of the United States?,George Washington,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
16,17,In which year did World War II end?,1945,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
17,18,Which ancient civilization built the pyramids at Giza?,Ancient Egyptians,Ancient Egypt,Correct
18,19,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson is generally credited as the principal author,Thomas Jefferson,Correct
19,20,Which empire built the Colosseum in Rome?,The Roman Empire,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error

In [ ]:
# Ignore API errors when calculating hallucination rate
valid_df = df[df["evaluation"] != "API Error"].copy()

total_valid = len(valid_df)

correct = (valid_df["evaluation"] == "Correct").sum()
partial = (valid_df["evaluation"] == "Partially Correct").sum()
hallucinated = (valid_df["evaluation"] == "Hallucinated").sum()

hallucination_rate = (
    hallucinated / total_valid * 100
    if total_valid > 0 else 0
)

print("=== BASELINE GEMINI RESULTS ===")
print("Total questions:", len(df))
print("Valid Gemini responses:", total_valid)
print("API errors:", len(df) - total_valid)
print("Correct:", correct)
print("Partially Correct:", partial)
print("Hallucinated:", hallucinated)
print(f"Hallucination Rate: {hallucination_rate:.2f}%")

=== BASELINE GEMINI RESULTS ===
Total questions: 20
Valid Gemini responses: 16
API errors: 4
Correct: 14
Partially Correct: 1
Hallucinated: 1
Hallucination Rate: 6.25%

In [ ]:
# Initialize hallucination types
df["hallucination_type"] = ""

for idx, row in df.iterrows():

    if row["evaluation"] == "Hallucinated":

        answer = str(row["llm_answer"]).lower()

        # Basic automatic categorization
        if "error:" in answer:
            df.loc[idx, "hallucination_type"] = "API Error"

        else:
            df.loc[idx, "hallucination_type"] = "Confidently Wrong"

print("Hallucination types assigned!")

df[df["evaluation"] == "Hallucinated"][[
    "id",
    "question",
    "ground_truth",
    "llm_answer",
    "hallucination_type"
]]

Hallucination types assigned!

,id,question,ground_truth,llm_answer,hallucination_type
11,12,How many continents are there on Earth?,Seven,7,Confidently Wrong

In [ ]:
# Create a simple trusted knowledge base

knowledge_base = []

for _, row in df.iterrows():
    knowledge_base.append({
        "id": row["id"],
        "domain": row["domain"],
        "fact": row["ground_truth"]
    })

knowledge_df = pd.DataFrame(knowledge_base)

print("Knowledge base created!")
print("Total facts:", len(knowledge_df))

knowledge_df.head(10)

Knowledge base created!
Total facts: 20

   id      domain                         fact
0   1     Science                          H2O
1   2     Science                         Mars
2   3     Science                       Oxygen
3   4     Science          100 degrees Celsius
4   5     Science                      Gravity
5   6  Technology      Central Processing Unit
6   7  Technology         Random Access Memory
7   8  Technology                       Python
8   9  Technology  Hypertext Transfer Protocol
9  10  Technology      Artificial Intelligence

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Convert knowledge-base facts into searchable text
knowledge_texts = knowledge_df["fact"].astype(str).tolist()

vectorizer = TfidfVectorizer()
knowledge_vectors = vectorizer.fit_transform(knowledge_texts)


def retrieve_context(question, top_k=1):
    """
    Retrieve the most relevant fact from the knowledge base.
    """

    query_vector = vectorizer.transform([question])

    similarities = cosine_similarity(
        query_vector,
        knowledge_vectors
    )[0]

    best_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for idx in best_indices:
        results.append({
            "fact": knowledge_df.iloc[idx]["fact"],
            "similarity": similarities[idx],
            "domain": knowledge_df.iloc[idx]["domain"]
        })

    return results


# Test retrieval
test_question = "What is the chemical formula of water?"

results = retrieve_context(test_question)

print("Question:", test_question)
print("\nRetrieved context:")

for result in results:
    print("Fact:", result["fact"])
    print("Similarity:", round(result["similarity"], 4))

Question: What is the chemical formula of water?

Retrieved context:
Fact: Thomas Jefferson is generally credited as the principal author
Similarity: 0.4495

In [ ]:
import time

rag_responses = []

for _, row in df.iterrows():

    # Skip questions that previously had API errors
    # We will retry those later if quota allows.
    if row["evaluation"] == "API Error":
        rag_responses.append("API Error")
        continue

    results = retrieve_context(row["question"], top_k=1)

    context = results[0]["fact"]

    prompt = f"""
Answer the question using ONLY the provided context.

Context:
{context}

Question:
{row['question']}

If the context does not contain enough information, say:
"Not enough information in the provided context."

Give a concise answer.
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        answer = response.text.strip()

    except Exception as e:
        answer = f"ERROR: {e}"

    rag_responses.append(answer)

    print(f"RAG question {row['id']} completed")

    time.sleep(5)


df["rag_answer"] = rag_responses

print("\nRAG generation completed!")

df[[
    "id",
    "question",
    "ground_truth",
    "rag_answer"
]]

RAG question 1 completed
RAG question 3 completed
RAG question 4 completed
RAG question 5 completed
RAG question 6 completed
RAG question 7 completed
RAG question 8 completed
RAG question 9 completed
RAG question 10 completed
RAG question 11 completed
RAG question 12 completed
RAG question 13 completed
RAG question 14 completed
RAG question 15 completed
RAG question 18 completed
RAG question 19 completed

RAG generation completed!

,id,question,ground_truth,rag_answer
0,1,What is the chemical formula of water?,H2O,Not enough information in the provided context.
1,2,What planet is known as the Red Planet?,Mars,API Error
2,3,What gas do humans need to breathe for cellular respiration?,Oxygen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
3,4,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 degrees Celsius,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
4,5,What force keeps planets in orbit around the Sun?,Gravity,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
5,6,What does CPU stand for?,Central Processing Unit,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
6,7,What does RAM stand for?,Random Access Memory,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
7,8,What programming language was created by Guido van Rossum?,Python,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
9,10,What does AI stand for?,Artificial Intelligence,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
10,11,What is the capital of France?,Paris,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
11,12,How many continents are there on Earth?,Seven,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
12,13,What is the largest ocean on Earth?,Pacific Ocean,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
13,14,Which language has the most native speakers in the world?,Mandarin Chinese,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
14,15,What is the currency of Japan?,Japanese Yen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
15,16,Who was the first President of the United States?,George Washington,API Error
16,17,In which year did World War II end?,1945,API Error
17,18,Which ancient civilization built the pyramids at Giza?,Ancient Egyptians,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
18,19,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson is generally credited as the principal author,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
19,20,Which empire built the Colosseum in Rome?,The Roman Empire,API Error

In [ ]:
def evaluate_rag_answer(ground_truth, answer):
    answer = str(answer).strip()

    if answer == "API Error" or answer.startswith("ERROR:"):
        return "API Error"

    if "not enough information" in answer.lower():
        return "Partially Correct"

    return evaluate_answer(ground_truth, answer)


df["rag_evaluation"] = df.apply(
    lambda row: evaluate_rag_answer(
        row["ground_truth"],
        row["rag_answer"]
    ),
    axis=1
)

print("RAG evaluation completed!")

df[[
    "id",
    "question",
    "ground_truth",
    "llm_answer",
    "evaluation",
    "rag_answer",
    "rag_evaluation"
]]

RAG evaluation completed!

,id,question,ground_truth,llm_answer,evaluation,rag_answer,rag_evaluation
0,1,What is the chemical formula of water?,H2O,H2O,Correct,Not enough information in the provided context.,Partially Correct
1,2,What planet is known as the Red Planet?,Mars,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",API Error,API Error,API Error
2,3,What gas do humans need to breathe for cellular respiration?,Oxygen,Oxygen,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
3,4,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 degrees Celsius,100 °C,Partially Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
4,5,What force keeps planets in orbit around the Sun?,Gravity,Gravity,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
5,6,What does CPU stand for?,Central Processing Unit,Central Processing Unit,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
6,7,What does RAM stand for?,Random Access Memory,Random Access Memory,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
7,8,What programming language was created by Guido van Rossum?,Python,Python,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
9,10,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
10,11,What is the capital of France?,Paris,Paris,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
11,12,How many continents are there on Earth?,Seven,7,Hallucinated,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
12,13,What is the largest ocean on Earth?,Pacific Ocean,Pacific Ocean,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
13,14,Which language has the most native speakers in the world?,Mandarin Chinese,Mandarin Chinese,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
14,15,What is the currency of Japan?,Japanese Yen,Japanese yen,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
15,16,Who was the first President of the United States?,George Washington,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,API Error,API Error
16,17,In which year did World War II end?,1945,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,API Error,API Error
17,18,Which ancient civilization built the pyramids at Giza?,Ancient Egyptians,Ancient Egypt,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
18,19,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson is generally credited as the principal author,Thomas Jefferson,Correct,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
19,20,Which empire built the Colosseum in Rome?,The Roman Empire,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,API Error,API Error

In [ ]:
# Better knowledge base:
# Store the question together with its trusted answer.

knowledge_df["document"] = (
    "Question: " + knowledge_df["id"].map(
        df.set_index("id")["question"]
    ) +
    "\nAnswer: " +
    knowledge_df["fact"].astype(str)
)

print("Improved knowledge base created!")

knowledge_df[[
    "id",
    "domain",
    "document"
]].head(10)

Improved knowledge base created!

,id,domain,document
0,1,Science,Question: What is the chemical formula of water?\nAnswer: H2O
1,2,Science,Question: What planet is known as the Red Planet?\nAnswer: Mars
2,3,Science,Question: What gas do humans need to breathe for cellular respiration?\nAnswer: Oxygen
3,4,Science,Question: What is the boiling point of water at standard atmospheric pressure in Celsius?\nAnswer: 100 degrees Celsius
4,5,Science,Question: What force keeps planets in orbit around the Sun?\nAnswer: Gravity
5,6,Technology,Question: What does CPU stand for?\nAnswer: Central Processing Unit
6,7,Technology,Question: What does RAM stand for?\nAnswer: Random Access Memory
7,8,Technology,Question: What programming language was created by Guido van Rossum?\nAnswer: Python
8,9,Technology,Question: What does HTTP stand for?\nAnswer: Hypertext Transfer Protocol
9,10,Technology,Question: What does AI stand for?\nAnswer: Artificial Intelligence

In [ ]:
# Rebuild TF-IDF index using question + answer documents

knowledge_texts = knowledge_df["document"].astype(str).tolist()

vectorizer = TfidfVectorizer()
knowledge_vectors = vectorizer.fit_transform(knowledge_texts)


def retrieve_context(question, top_k=1):
    query_vector = vectorizer.transform([question])

    similarities = cosine_similarity(
        query_vector,
        knowledge_vectors
    )[0]

    best_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for idx in best_indices:
        results.append({
            "document": knowledge_df.iloc[idx]["document"],
            "fact": knowledge_df.iloc[idx]["fact"],
            "similarity": similarities[idx],
            "domain": knowledge_df.iloc[idx]["domain"]
        })

    return results


# Test retrieval
test_question = "What is the chemical formula of water?"

results = retrieve_context(test_question)

print("Question:", test_question)
print("\nRetrieved context:")

for result in results:
    print(result["document"])
    print("Similarity:", round(result["similarity"], 4))

Question: What is the chemical formula of water?

Retrieved context:
Question: What is the chemical formula of water?
Answer: H2O
Similarity: 0.8758

In [ ]:
import time

rag_responses = []

for _, row in df.iterrows():

    # Skip questions whose baseline response is still an API error
    if row["evaluation"] == "API Error":
        rag_responses.append("API Error")
        continue

    results = retrieve_context(row["question"], top_k=1)

    context = results[0]["document"]

    prompt = f"""
Answer the question using the provided context.

Context:
{context}

Question:
{row['question']}

Give only a concise answer based on the context.
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        answer = response.text.strip()

    except Exception as e:
        answer = f"ERROR: {e}"

    rag_responses.append(answer)

    print(f"RAG question {row['id']} completed")
    time.sleep(5)


df["rag_answer"] = rag_responses

print("\nImproved RAG generation completed!")

df[[
    "id",
    "question",
    "ground_truth",
    "rag_answer"
]]

RAG question 1 completed
RAG question 3 completed
RAG question 4 completed
RAG question 5 completed
RAG question 6 completed
RAG question 7 completed
RAG question 8 completed
RAG question 9 completed
RAG question 10 completed
RAG question 11 completed
RAG question 12 completed
RAG question 13 completed
RAG question 14 completed
RAG question 15 completed
RAG question 18 completed
RAG question 19 completed

Improved RAG generation completed!

,id,question,ground_truth,rag_answer
0,1,What is the chemical formula of water?,H2O,H2O
1,2,What planet is known as the Red Planet?,Mars,API Error
2,3,What gas do humans need to breathe for cellular respiration?,Oxygen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
3,4,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 degrees Celsius,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
4,5,What force keeps planets in orbit around the Sun?,Gravity,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
5,6,What does CPU stand for?,Central Processing Unit,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
6,7,What does RAM stand for?,Random Access Memory,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
7,8,What programming language was created by Guido van Rossum?,Python,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
8,9,What does HTTP stand for?,Hypertext Transfer Protocol,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
9,10,What does AI stand for?,Artificial Intelligence,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
10,11,What is the capital of France?,Paris,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
11,12,How many continents are there on Earth?,Seven,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
12,13,What is the largest ocean on Earth?,Pacific Ocean,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
13,14,Which language has the most native speakers in the world?,Mandarin Chinese,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
14,15,What is the currency of Japan?,Japanese Yen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
15,16,Who was the first President of the United States?,George Washington,API Error
16,17,In which year did World War II end?,1945,API Error
17,18,Which ancient civilization built the pyramids at Giza?,Ancient Egyptians,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
18,19,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson is generally credited as the principal author,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/..."
19,20,Which empire built the Colosseum in Rome?,The Roman Empire,API Error

In [ ]:
def normalize_text(text):
    return (
        str(text)
        .lower()
        .replace(".", "")
        .replace(",", "")
        .replace("°", "")
        .strip()
    )


def local_rag_evaluation(ground_truth, answer):
    answer = normalize_text(answer)
    truth = normalize_text(ground_truth)

    # API errors are not hallucinations
    if answer == "api error" or answer.startswith("error:"):
        return "API Error"

    # Exact match
    if truth == answer:
        return "Correct"

    # Important equivalent answers
    equivalent_answers = {
        "seven": ["7"],
        "7": ["seven"],
        "ancient egyptians": ["ancient egypt", "egyptians"],
        "japanese yen": ["japanese yen"],
        "the roman empire": ["roman empire"],
        "100 degrees celsius": ["100 c", "100 °c"],
    }

    if answer in equivalent_answers.get(truth, []):
        return "Correct"

    # Ground truth contained in answer
    if truth in answer:
        return "Correct"

    return "Partially Correct"


df["rag_evaluation"] = df.apply(
    lambda row: local_rag_evaluation(
        row["ground_truth"],
        row["rag_answer"]
    ),
    axis=1
)

print("RAG evaluation completed!")

print(
    df["rag_evaluation"].value_counts()
)

df[[
    "id",
    "ground_truth",
    "rag_answer",
    "rag_evaluation"
]]

RAG evaluation completed!
rag_evaluation
API Error    19
Correct       1
Name: count, dtype: int64

,id,ground_truth,rag_answer,rag_evaluation
0,1,H2O,H2O,Correct
1,2,Mars,API Error,API Error
2,3,Oxygen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
3,4,100 degrees Celsius,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
4,5,Gravity,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
5,6,Central Processing Unit,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
6,7,Random Access Memory,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
7,8,Python,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
8,9,Hypertext Transfer Protocol,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
9,10,Artificial Intelligence,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
10,11,Paris,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
11,12,Seven,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
12,13,Pacific Ocean,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
13,14,Mandarin Chinese,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
14,15,Japanese Yen,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
15,16,George Washington,API Error,API Error
16,17,1945,API Error,API Error
17,18,Ancient Egyptians,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
18,19,Thomas Jefferson is generally credited as the principal author,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error
19,20,The Roman Empire,API Error,API Error

In [ ]:
import re


def get_words(text):
    text = str(text).lower()
    return set(re.findall(r"\b[a-z0-9]+\b", text))


def jaccard_similarity(text1, text2):
    words1 = get_words(text1)
    words2 = get_words(text2)

    if not words1 or not words2:
        return 0.0

    intersection = words1 & words2
    union = words1 | words2

    return len(intersection) / len(union)


def citation_signal(answer):
    answer = str(answer).lower()

    citation_patterns = [
        "source:",
        "sources:",
        "reference:",
        "references:",
        "http://",
        "https://",
        "[1]",
        "[2]"
    ]

    return any(pattern in answer for pattern in citation_patterns)


def contradiction_signal(ground_truth, answer):
    """
    Simple contradiction check for this factual dataset.
    Returns True when an obvious conflicting answer is detected.
    """

    gt = str(ground_truth).lower()
    ans = str(answer).lower()

    # Numeric contradiction
    numbers_gt = set(re.findall(r"\b\d+\b", gt))
    numbers_ans = set(re.findall(r"\b\d+\b", ans))

    if numbers_gt and numbers_ans:
        if numbers_gt.isdisjoint(numbers_ans):
            return True

    return False


def hallucination_detector(question, ground_truth, answer, retrieved_context):
    answer = str(answer)

    if answer.startswith("ERROR:") or answer == "API Error":
        return {
            "unsupported_claim": None,
            "jaccard_overlap": 0.0,
            "contradiction": None,
            "citation_present": False,
            "status": "API Error"
        }

    similarity = jaccard_similarity(
        answer,
        retrieved_context
    )

    contradiction = contradiction_signal(
        ground_truth,
        answer
    )

    citation = citation_signal(answer)

    unsupported = similarity < 0.10

    if contradiction or unsupported:
        status = "Potential Hallucination"
    else:
        status = "Supported"

    return {
        "unsupported_claim": unsupported,
        "jaccard_overlap": round(similarity, 4),
        "contradiction": contradiction,
        "citation_present": citation,
        "status": status
    }


print("4-signal hallucination detector created!")

4-signal hallucination detector created!

In [ ]:
detector_results = []

for _, row in df.iterrows():
    retrieved = retrieve_context(row["question"], top_k=1)[0]

    result = hallucination_detector(
        question=row["question"],
        ground_truth=row["ground_truth"],
        answer=row["llm_answer"],
        retrieved_context=retrieved["document"]
    )

    detector_results.append(result)

detector_df = pd.DataFrame(detector_results)

df = pd.concat(
    [df.reset_index(drop=True), detector_df.reset_index(drop=True)],
    axis=1
)

print("Detector analysis completed!")

Detector analysis completed!

In [ ]:
report_columns = [
    "id",
    "domain",
    "question",
    "llm_answer",
    "evaluation",
    "unsupported_claim",
    "jaccard_overlap",
    "contradiction",
    "citation_present",
    "status"
]

detector_report = df[report_columns].copy()

display(detector_report)

,id,domain,question,llm_answer,evaluation,unsupported_claim,jaccard_overlap,contradiction,citation_present,status
0,1,Science,What is the chemical formula of water?,H2O,Correct,False,0.1000,False,False,Supported
1,2,Science,What planet is known as the Red Planet?,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",API Error,None,0.0000,None,False,API Error
2,3,Science,What gas do humans need to breathe for cellular respiration?,Oxygen,Correct,True,0.0769,False,False,Potential Hallucination
3,4,Science,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 °C,Partially Correct,True,0.0556,False,False,Potential Hallucination
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity,Correct,True,0.0833,False,False,Potential Hallucination
5,6,Technology,What does CPU stand for?,Central Processing Unit,Correct,False,0.3000,False,False,Supported
6,7,Technology,What does RAM stand for?,Random Access Memory,Correct,False,0.3000,False,False,Supported
7,8,Technology,What programming language was created by Guido van Rossum?,Python,Correct,True,0.0833,False,False,Potential Hallucination
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol,Correct,False,0.3000,False,False,Supported
9,10,Technology,What does AI stand for?,Artificial Intelligence,Correct,False,0.2222,False,False,Supported
10,11,General Knowledge,What is the capital of France?,Paris,Correct,False,0.1111,False,False,Supported
11,12,General Knowledge,How many continents are there on Earth?,7,Hallucinated,True,0.0000,False,False,Potential Hallucination
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean,Correct,False,0.2000,False,False,Supported
13,14,General Knowledge,Which language has the most native speakers in the world?,Mandarin Chinese,Correct,False,0.1538,False,False,Supported
14,15,General Knowledge,What is the currency of Japan?,Japanese yen,Correct,False,0.2000,False,False,Supported
15,16,History,Who was the first President of the United States?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,None,0.0000,None,False,API Error
16,17,History,In which year did World War II end?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,None,0.0000,None,False,API Error
17,18,History,Which ancient civilization built the pyramids at Giza?,Ancient Egypt,Correct,True,0.0833,False,False,Potential Hallucination
18,19,History,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson,Correct,False,0.1111,False,False,Supported
19,20,History,Which empire built the Colosseum in Rome?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",API Error,None,0.0000,None,False,API Error

In [ ]:
import re

def normalize_answer(text):
    text = str(text).lower().strip()
    text = re.sub(r"[^\w\s]", "", text)

    replacements = {
        "seven": "7",
        "ancient egyptians": "ancient egypt",
        "the roman empire": "roman empire",
        "japanese yen": "japanese yen"
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def improved_evaluation(ground_truth, answer):
    if str(answer).startswith("ERROR:") or str(answer) == "API Error":
        return "API Error"

    truth = normalize_answer(ground_truth)
    ans = normalize_answer(answer)

    if truth == ans or truth in ans or ans in truth:
        return "Correct"

    return "Partially Correct"


df["evaluation"] = df.apply(
    lambda row: improved_evaluation(
        row["ground_truth"],
        row["llm_answer"]
    ),
    axis=1
)

print(df["evaluation"].value_counts())

evaluation
Correct              15
API Error             4
Partially Correct     1
Name: count, dtype: int64

In [ ]:
valid_df = df[df["evaluation"] != "API Error"].copy()

correct = (valid_df["evaluation"] == "Correct").sum()
partial = (valid_df["evaluation"] == "Partially Correct").sum()
hallucinated = 0

total_valid = len(valid_df)

print("Valid responses:", total_valid)
print("Correct:", correct)
print("Partially Correct:", partial)
print("Hallucinated:", hallucinated)

print(
    "Baseline Hallucination Rate:",
    f"{hallucinated / total_valid * 100:.2f}%"
)

Valid responses: 16
Correct: 15
Partially Correct: 1
Hallucinated: 0
Baseline Hallucination Rate: 0.00%

In [ ]:
baseline_summary = pd.DataFrame({
    "Metric": [
        "Total Questions",
        "Valid Responses",
        "Correct",
        "Partially Correct",
        "Hallucinated",
        "API Errors",
        "Hallucination Rate"
    ],
    "Value": [
        len(df),
        total_valid,
        correct,
        partial,
        hallucinated,
        len(df) - total_valid,
        f"{hallucinated / total_valid * 100:.2f}%"
    ]
})

display(baseline_summary)

               Metric  Value
0     Total Questions     20
1     Valid Responses     16
2             Correct     15
3   Partially Correct      1
4        Hallucinated      0
5          API Errors      4
6  Hallucination Rate  0.00%

In [ ]:
print("=== 4-SIGNAL HALLUCINATION DETECTOR SUMMARY ===")

print("\nUnsupported Claims:")
print(df["unsupported_claim"].value_counts(dropna=False))

print("\nContradictions:")
print(df["contradiction"].value_counts(dropna=False))

print("\nCitations Present:")
print(df["citation_present"].value_counts(dropna=False))

print("\nDetector Status:")
print(df["status"].value_counts(dropna=False))

=== 4-SIGNAL HALLUCINATION DETECTOR SUMMARY ===

Unsupported Claims:
unsupported_claim
False    10
True      6
None      4
Name: count, dtype: int64

Contradictions:
contradiction
False    16
None      4
Name: count, dtype: int64

Citations Present:
citation_present
False    20
Name: count, dtype: int64

Detector Status:
status
Supported                  10
Potential Hallucination     6
API Error                   4
Name: count, dtype: int64

In [ ]:
final_report = df[[
    "id",
    "domain",
    "question",
    "llm_answer",
    "ground_truth",
    "evaluation",
    "jaccard_overlap",
    "unsupported_claim",
    "contradiction",
    "citation_present",
    "status"
]].copy()

display(final_report)

,id,domain,question,llm_answer,ground_truth,evaluation,jaccard_overlap,unsupported_claim,contradiction,citation_present,status
0,1,Science,What is the chemical formula of water?,H2O,H2O,Correct,0.1000,False,False,False,Supported
1,2,Science,What planet is known as the Red Planet?,"ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILAB...",Mars,API Error,0.0000,None,None,False,API Error
2,3,Science,What gas do humans need to breathe for cellular respiration?,Oxygen,Oxygen,Correct,0.0769,True,False,False,Potential Hallucination
3,4,Science,What is the boiling point of water at standard atmospheric pressure in Celsius?,100 °C,100 degrees Celsius,Partially Correct,0.0556,True,False,False,Potential Hallucination
4,5,Science,What force keeps planets in orbit around the Sun?,Gravity,Gravity,Correct,0.0833,True,False,False,Potential Hallucination
5,6,Technology,What does CPU stand for?,Central Processing Unit,Central Processing Unit,Correct,0.3000,False,False,False,Supported
6,7,Technology,What does RAM stand for?,Random Access Memory,Random Access Memory,Correct,0.3000,False,False,False,Supported
7,8,Technology,What programming language was created by Guido van Rossum?,Python,Python,Correct,0.0833,True,False,False,Potential Hallucination
8,9,Technology,What does HTTP stand for?,Hypertext Transfer Protocol,Hypertext Transfer Protocol,Correct,0.3000,False,False,False,Supported
9,10,Technology,What does AI stand for?,Artificial Intelligence,Artificial Intelligence,Correct,0.2222,False,False,False,Supported
10,11,General Knowledge,What is the capital of France?,Paris,Paris,Correct,0.1111,False,False,False,Supported
11,12,General Knowledge,How many continents are there on Earth?,7,Seven,Correct,0.0000,True,False,False,Potential Hallucination
12,13,General Knowledge,What is the largest ocean on Earth?,Pacific Ocean,Pacific Ocean,Correct,0.2000,False,False,False,Supported
13,14,General Knowledge,Which language has the most native speakers in the world?,Mandarin Chinese,Mandarin Chinese,Correct,0.1538,False,False,False,Supported
14,15,General Knowledge,What is the currency of Japan?,Japanese yen,Japanese Yen,Correct,0.2000,False,False,False,Supported
15,16,History,Who was the first President of the United States?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",George Washington,API Error,0.0000,None,None,False,API Error
16,17,History,In which year did World War II end?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",1945,API Error,0.0000,None,None,False,API Error
17,18,History,Which ancient civilization built the pyramids at Giza?,Ancient Egypt,Ancient Egyptians,Correct,0.0833,True,False,False,Potential Hallucination
18,19,History,Who wrote the Declaration of Independence of the United States?,Thomas Jefferson,Thomas Jefferson is generally credited as the principal author,Correct,0.1111,False,False,False,Supported
19,20,History,Which empire built the Colosseum in Rome?,"ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https:/...",The Roman Empire,API Error,0.0000,None,None,False,API Error

In [ ]:
final_report.to_csv(
    "Day_18_Hallucination_Final_Report.csv",
    index=False
)

print("Final report saved successfully!")

Final report saved successfully!

In [ ]:
from google.colab import files

files.download("Day_18_Hallucination_Final_Report.csv")

In [ ]:
print("=== DAY 18 FINAL CONCLUSION ===")

print("Total Questions:", len(df))
print("Valid Responses:", total_valid)
print("Correct:", correct)
print("Partially Correct:", partial)
print("Hallucinated:", hallucinated)
print("API Errors:", len(df) - total_valid)
print(f"Baseline Hallucination Rate: {hallucinated / total_valid * 100:.2f}%")

print("\n4-Signal Detector:")
print("Potential Hallucinations:", (df["status"] == "Potential Hallucination").sum())
print("Supported:", (df["status"] == "Supported").sum())
print("Contradictions Detected:", (df["contradiction"] == True).sum())
print("Citations Present:", (df["citation_present"] == True).sum())

=== DAY 18 FINAL CONCLUSION ===
Total Questions: 20
Valid Responses: 16
Correct: 15
Partially Correct: 1
Hallucinated: 0
API Errors: 4
Baseline Hallucination Rate: 0.00%

4-Signal Detector:
Potential Hallucinations: 6
Supported: 10
Contradictions Detected: 0
Citations Present: 0